Dev
petushka1/ruby-capstone pull request #45
Opened 2022-09-23 19:19 UTC by petushka1

## Ruby Capstone Group Project
### Scope and Flow

- [x] Set a Kanban board
- [x] Assing cards
- [x] Complete all tasks:
### Member 1 
   - [x] Create Item, Book, Label classes
   - [x] Built functionality for:
   - storing books and labels in files
   - reading books and labels from files
   - restoring Book label by ID
   - add new book and specify label (create new/select from list)
   - CLI to:
   -  list all books, 
   - list all labels, 
   - add the new book and its label  

### Member 2
   - [x] Create Music Albums, Genres classes
   - [x] Built functionality for:
   - storing albums and genres in files
   - reading albums and genres from files
   - add a new album and specify the genre
   - CLI to:
   -  list all Music Albums, 
   - list all Genres, 
   - add the new album and specify the genre  

### Member 3
   - [x] Create Games, Authors classes
   - [x] Built functionality for:
   - storing games and authors in files
   - reading games and authors from files
   - add a new game and specify the author
   - CLI to:
   -  list all Games, 
   - list all Authors, 
   - add the new game and specify its author  

### Requirements
:heavy_check_mark: Gitflow set correctly
:heavy_check_mark: DRY, KISS YAGNI principles followed
:heavy_check_mark: No linter error

2022-09-23 20:06 UTC, t-yanick requested changes
Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 20:06 UTC, t-yanick commented on README.md
> +
- [ ] Since this is a group project, it will be nice update your readme file with information pertaining to other group member

2022-09-23 20:06 UTC, t-yanick commented on README.md
> +
### Project documentation
Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

 - A description of the project.
 - A demo of the project features.
 - You should also highlight some interesting piece of code or something you built that you are very proud of.
 - You all should appear in the video and talk about the project.
 - For recording the video you can use the Zoom recording features while in a call with your peers.

Please your project is missing the above requirements, please kindly add them.

2022-09-24 07:48 UTC, petushka1 commented
## Changes completed

- [x] add all authors to the README file
- [x] Record presentation and add to README

2022-09-24 07:52 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @petushka1, @c3c1l1a ,and @ShaheerCH 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 11:30 UTC, merged